language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
#deploy:
# provider: heroku
# api_key: abc28d49-33d5-49bc-a128-4eff6e3c0818
# app: aqueous-shelf-32758
# run: "rake db:migrate"
# on:
#  all_branches: true